"""
CRAVE Phase 7 - PowerPoint Automation Agent
Programmatically builds .pptx presentations using Qwen3 json structures.
Features an interactive Preview UX flow before finalizing the save path.
"""

import os
import pptx
from pptx.util import Inches, Pt
import logging
import tempfile
import shutil
import time

logger = logging.getLogger("crave.agents.ppt")

class PPTAgent:
    def __init__(self):
        self.temp_dir = os.path.join(os.environ.get("CRAVE_ROOT", r"D:\CRAVE"), "data", "temp_ppt")
        os.makedirs(self.temp_dir, exist_ok=True)

    def build_presentation(self, title: str, slides_data: list) -> str:
        """
        Creates a presentation from JSON array of slides.
        Example slides_data:
        [
            {"title": "Introduction", "content": ["Bullet 1", "Bullet 2"]},
            {"title": "Architecture", "content": ["Node.js API", "React Frontend"]}
        ]
        """
        try:
            prs = pptx.Presentation()
            
            # Title Slide (Layout 0)
            title_slide_layout = prs.slide_layouts[0]
            slide = prs.slides.add_slide(title_slide_layout)
            title_shape = slide.shapes.title
            subtitle_shape = slide.placeholders[1]
            
            title_shape.text = title
            subtitle_shape.text = "Generated by CRAVE AI"

            # Content Slides (Layout 1)
            bullet_slide_layout = prs.slide_layouts[1]
            
            for slide_dict in slides_data:
                slide_obj = prs.slides.add_slide(bullet_slide_layout)
                shapes = slide_obj.shapes
                
                title_shape = shapes.title
                body_shape = shapes.placeholders[1]
                
                title_shape.text = slide_dict.get("title", "Untitled Slide")
                
                tf = body_shape.text_frame
                content = slide_dict.get("content", [])
                
                if content:
                    tf.text = content[0]
                    for point in content[1:]:
                        p = tf.add_paragraph()
                        p.text = point
                        p.level = 0
                        
            # Save to temporary preview location
            temp_path = os.path.join(self.temp_dir, "CRAVE_Preview.pptx")
            prs.save(temp_path)
            
            return self._preview_and_save_flow(temp_path)
            
        except Exception as e:
            logger.error(f"Failed to build PPTX: {e}")
            return f"ERROR: PowerPoint generation failed - {e}"

    def _preview_and_save_flow(self, temp_path: str) -> str:
        """
        Opens the PPTX for user review and asks for the final save destination.
        """
        if os.name == 'nt':
            print("\n[PPTAgent] Launching PowerPoint Preview...")
            os.startfile(temp_path)
        else:
            return f"SUCCESS: Saved to {temp_path} (Cannot auto-open on Linux)"
            
        # Give the OS a second to spawn the PPT window
        time.sleep(1)
        
        print("\n" + "="*50)
        print("  CRAVE PPT REVIEW MODE")
        print("="*50)
        print(f"I have opened the presentation for you to review.")
        print("Make any manual changes you want inside PowerPoint and hit SAVE.")
        print("When you are perfectly happy with it, tell me where to permanently save it.")
        
        try:
            # Simple terminal prompt for v1 UX. 
            # In Phase 10 this hooks into the actual Orb speech/text input wait-state.
            final_path = input("\nEnter full path to save (or type 'discard'): ").strip()
            
            if final_path.lower() in ["discard", "cancel", "no"]:
                os.remove(temp_path)
                return "ACTION CANCELED: Presentation discarded."
                
            if not final_path.endswith(".pptx"):
                final_path += ".pptx"
                
            shutil.copy2(temp_path, final_path)
            os.remove(temp_path) # Clean up temp
            
            return f"SUCCESS: Presentation finalized and saved strictly to {final_path}."
            
        except KeyboardInterrupt:
            return "ERROR: Flow interrupted."
